export const cardsData = [
  {
    id: 1,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGg8W.jpg" alt="Utopia World Hotel"/>',
    country: "Турция",
    rating: "st5",
    title: "Utopia World",
    place: "Каргыджак (Алания)",
    meal: "all-inclusive",
    holiday: "beach",
    distance: "1st-line",
    beach: "pebble",
    price: "99 700",
    href: "hotel-tour.html?id=1",
  },
  {
    id: 2,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGoXd.jpg" alt="Club Hotel Anjeliq"/>',
    country: "Турция",
    rating: "st4",
    title: "Club Hotel Anjeliq",
    place: "Кестель в Алании",
    meal: "all-inclusive",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    price: "72 800",
    href: "hotel-tour.html?id=2",
  },
  {
    id: 3,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGyvw.jpg" alt="Rubi Hotel"/>',
    country: "Турция",
    rating: "st5",
    title: "Rubi Hotel",
    place: "Авсаллар в Алании",
    meal: "three-meals",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    price: "71 600",
    href: "hotel-tour.html?id=3",
  },
  {
    id: 4,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGyZu.jpg" alt="Hotel Throne Beach Resort & Spa"/>',
    country: "Турция",
    rating: "st5",
    title: "Throne Beach Resort & Spa",
    meal: "three-meals",
    holiday: "excursion",
    distance: "2st-line",
    beach: "sand-pebble",
    place: "Карабурун в Алании",
    price: "80 400",
    href: "hotel-tour.html?id=4",
  },
  {
    id: 5,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGod1.jpg" alt="Kleopatra Smile"/>',
    country: "Турция",
    rating: "st3",
    title: "Kleopatra Smile",
    meal: "three-meals",
    holiday: "beach",
    distance: "1st-line",
    beach: "sandy",
    place: "Алания",
    price: "55 900",
    href: "hotel-tour.html?id=5",
  },
  {
    id: 6,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGyCf.jpg" alt="Asena Hotel"/>',
    country: "Турция",
    rating: "st3",
    title: "Asena Hotel",
    meal: "two-meals",
    holiday: "beach",
    distance: "2st-line",
    beach: "sandy",
    place: "Кушадасы",
    price: "57 400",
    href: "hotel-tour.html?id=6",
  },
  {
    id: 7,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGorS.jpg" alt="Hotel Belport Beach"/>',
    country: "Турция",
    rating: "st4",
    title: "Belport Beach",
    meal: "all-inclusive",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    place: "Бельдиби в Кемере",
    price: "62 000",
    href: "hotel-tour.html?id=7",
  },
  {
    id: 8,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGw0F.jpg" alt="Holiday Garden Resort"/>',
    country: "Турция",
    rating: "st5",
    title: "Holiday Garden Resort",
    meal: "three-meals",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    place: "Окурджалар в Алании",
    price: "69 700",
    href: "hotel-tour.html?id=8",
  },
  {
    id: 9,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGgiZ.jpg" alt="hotel Kaliptus"/>',
    country: "Турция",
    rating: "st2",
    title: "Kaliptus",
    meal: "single-meal",
    holiday: "beach",
    distance: "3st-line",
    beach: "pebble",
    place: "город Кемер в Кемере",
    price: "55 700",
    href: "hotel-tour.html?id=9",
  },
  {
    id: 10,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGqij.jpg" alt="Kata Sea Breeze Resort"/>',
    country: "Тайланд",
    rating: "st3",
    title: "Kata Sea Breeze Resort",
    meal: "three-meals",
    holiday: "beach",
    distance: "2st-line",
    beach: "sandy",
    place: "Ката на Пхукете",
    price: "95 700",
    href: "hotel-tour.html?id=10",
  },
  {
    id: 11,
    class: "card",
    img: '<img src="https://i.yapx.ru/WGzVz.jpg" alt="Faraana Heights Resort"/>',
    country: "Египет",
    rating: "st4",
    title: "Faraana Heights Resort",
    meal: "three-meals",
    holiday: "beach",
    distance: "2st-line",
    beach: "sandy",
    place: "Набк-Бей в Шарм-эль-Шейхе",
    price: "90 700",
    href: "hotel-tour.html?id=11",
  },
  {
    id: 12,
    class: "card",
    img: '<img src="https://i.yapx.ru/WHHgO.jpg" alt="Fujairah Rotana Resort And Spa"/>',
    country: "ОАЭ",
    rating: "st5",
    title: "Fujairah Rotana Resort And Spa",
    meal: "three-meals",
    holiday: "beach",
    distance: "1st-line",
    beach: "sandy",
    place: "Фуджейра",
    price: "90 700",
    href: "hotel-tour.html?id=12",
  },
  {
    id: 13,
    class: "card",
    img: '<img src="https://i.yapx.ru/WHIN1.jpg" alt="Ibis Phuket Patong"/>',
    country: "Тайланд",
    rating: "st3",
    title: "Ibis Phuket Patong",
    meal: "three-meals",
    holiday: "beach",
    distance: "3st-line",
    beach: "sandy",
    place: "Патонг на Пхукете",
    price: "96 900",
    href: "hotel-tour.html?id=13",
  },
  {
    id: 14,
    class: "card",
    img: '<img src="https://i.yapx.ru/WHIqf.jpg" alt="Naithonburi Beach Resort"/>',
    country: "Тайланд",
    rating: "st4",
    title: "Naithonburi Beach Resort",
    meal: "three-meals",
    holiday: "beach",
    distance: "2st-line",
    beach: "sandy",
    place: "Найтон на Пхукете",
    price: "98 700",
    href: "hotel-tour.html?id=14",
  }
];
