export const cardsData = [
  {
    id: 1,
    class: "card",
    img: '<img src="../img/hotels/Utopia-World.jpg" alt="hotel Utopia World"/>',
    country: "Турция",
    rating: "st5",
    title: "Utopia World",
    place: "Каргыджак (Алания)",
    meal: "all-inclusive",
    holiday: "beach",
    distance: "1st-line",
    beach: "pebble",
    price: "99 700"
  },
  {
    id: 2,
    class: "card",
    img: '<img src="../img/hotels/Artemis-Princess.jpg" alt="hotel Artemis Princess"/>',
    country: "Турция",
    rating: "st4",
    title: "Artemis Princess",
    place: "Алания",
    meal: "all-inclusive",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    price: "97 500"
  },
  {
    id: 3,
    class: "card",
    img: '<img src="../img/hotels/Blue-Bay-Platinum.jpg" alt="hotel Blue Bay Platinum"/>',
    country: "Турция",
    rating: "st5",
    title: "Blue Bay Platinum",
    place: "Мармарис",
    meal: "three-meals",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    price: "95 600",
  },
  {
    id: 4,
    class: "card",
    img: '<img src="../img/hotels/Ideal-Panorama.jpg" alt="hotel Ideal Panorama Holiday Village"/>',
    country: "Турция",
    rating: "st4",
    title: "Ideal Panorama Holiday Village",
    meal: "three-meals",
    holiday: "excursion",
    distance: "1st-line",
    beach: "sand-pebble",
    place: "Сителер в Мармарисе",
    price: "96 400",
  },
  {
    id: 5,
    class: "card",
    img: '<img src="../img/hotels/Casa&Blanca.jpg" alt="Casa & Blanca Beach Hotel"/>',
    country: "Турция",
    rating: "st4",
    title: "Casa & Blanca Beach Hotel",
    meal: "three-meals",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    place: "Ичмелер в Мармарисе",
    price: "97 300",
  },
  {
    id: 6,
    class: "card",
    img: '<img src="../img/hotels/Aegean-Park.jpg" alt="hotel Aegean Park"/>',
    country: "Турция",
    rating: "st3",
    title: "Aegean Park",
    meal: "two-meals",
    holiday: "beach",
    distance: "2st-line",
    beach: "sand-pebble",
    place: "Мармарис",
    price: "84 400",
  },
  {
    id: 7,
    class: "card",
    img: '<img src="../img/hotels/Hotel-Sinatra.jpg" alt="Hotel Sinatra"/>',
    country: "Турция",
    rating: "st4",
    title: "Hotel Sinatra",
    meal: "all-inclusive",
    holiday: "beach",
    distance: "1st-line",
    beach: "sand-pebble",
    place: "Чамьюва в Кемере",
    price: "89 000",
  },
  {
    id: 8,
    class: "card",
    img: '<img src="../img/hotels/Sonnen-Hotel.jpg" alt="Sonnen Hotel"/>',
    country: "Турция",
    rating: "st3",
    title: "Sonnen Hotel",
    meal: "three-meals",
    holiday: "beach",
    distance: "2st-line",
    beach: "sand-pebble",
    place: "Мармарис ",
    price: "87 400",
  },
  {
    id: 9,
    class: "card",
    img: '<img src="../img/hotels/Kaliptus.jpg" alt="hotel Kaliptus"/>',
    country: "Турция",
    rating: "st2",
    title: "Kaliptus",
    meal: "single-meal",
    holiday: "beach",
    distance: "3st-line",
    beach: "sandy",
    place: "Кемер",
    price: "82 000",
  }
];
